# -*- coding: utf-8 -*-
"""conbvert spech to texttttask3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/121XZH_yA5fzqud7Vk6Dc0gme8MWbWRvX
"""

# !pip install transformers -q

# !pip install gradio -q

from transformers import pipeline

p = pipeline("automatic-speech-recognition")

import gradio as gr
import time

def transcribe(audio, state=""):
    time.sleep(3)
    text = p(audio)["text"]
    state += text + " "
    return state, state

gr.Interface(
    fn=transcribe,
    inputs=[
        gr.inputs.Audio(source="microphone", type="filepath"),
        'state'
    ],
    outputs=[
        "textbox",
        "state"
    ],
    live=True).launch()





